a에 1이라는 숫자값을 대입하였다. int는 정수를 의미한다.

In [1]:
a=1; print(type(a))

<class 'int'>


이번에는 똑같은 숫자값을 대입하였으나, 소수를 의미하는 float를 취하였다.

In [2]:
a=1; a=float(a); print(type(a))

<class 'float'>


a에 실제로는 소수값을 입력하여도 int로 정의하였기 때문에 int값이 출력된다.

In [4]:
a=1.2; a=int(a); print(type(a))

<class 'int'>


a가 실제로는 스트링이지만 a를 list로 정의하였기 때문에 a의class는 리스트가 된다.  

In [5]:
a='123'; a=list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


아래처럼 줄을 바꾸거나 ; 을 붙이지 않고 바로 다른 명령을 할 경우 syntax에러가 발생한다.

In [21]:
a='123[4]' print(type(a))

SyntaxError: invalid syntax (<ipython-input-21-d7810095e6b1>, line 1)

1,2,3을 요소로 하는 a리스트를 작성하였다.

In [26]:
a=[1,2,3]
print(type(a))

<class 'list'>


(1,2,3)과 (3,8,0) 두 개의 튜플을 요소로 갖는 리스트를 작성하였다.

In [27]:
a=[(1,2,3), (3,8,0)]; print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

위에 작성하였던 a에 대하여 array함수를 적용하였다. 그 이전에 numeric python 즉 numpy를 import(불러오기)를 하였다. 즉, a리스트에 대하여 array함수를 즉시 적용할 수 있는 상태를 만들었다고 볼 수 있다. a리스트에 array함수를 적용하여 만든 결과를 b라고 하자. 이 때 b의 class는 numpy.ndarray가 된다.

In [50]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


이렇게 생성한 ndarray, 즉 배열을 가지고 연산을 할 수 있을까? 우선 b와 b를 곱해보았다.

In [64]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [65]:
c=print(b*2)
c

[[ 2  4  6]
 [ 6 16  0]]


In [66]:
print(b+b)

[[ 2  4  6]
 [ 6 16  0]]


In [67]:
e=print(b-2)
e

[[-1  0  1]
 [ 1  6 -2]]


b와c를 연산하려고 하니 type 에러가 발생하였다. 왜 그럴까? type에러가 발생한 점으로 미루어보아 b와 c의 종류가 달라서 연산이 불가능하다고 추측하였다.

In [68]:
d=print(c+b)
c+b

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

분명히 b의 class는 numpy.ndarray라는 점을 확인하였고, c는 b를 두배만큼 곱한 배열이다. 그런데 c의 class가 배열이 아닌 nonetype이다. b와 숫자, c와 숫자는 연산이 가능하지만 b와c가 서로 연산이 불가능한 원인을 발견하였다. 그렇다면 c의 class를 numpy.ndarray로 설정하면 연산이 가능해질까?

In [69]:
print(type(b));
print(type(c))

<class 'numpy.ndarray'>
<class 'NoneType'>


c의 class를 np.ndarray로 정의하였다. 이제 b와 c의 연산이 가능해질까?

In [70]:
c=np.ndarray(c)
print(type(c))

<class 'numpy.ndarray'>


전혀 예상하지 못 한 결과이다.. c와b와 같은 배열이 행렬의 모양을 하고 있지만 행렬처럼 평범한 계산은 불가능한 듯하다. b와 c는 모두 2차원 배열이고, 우리가 원하는 사칙연산은 행렬에서 가능한 듯 하다.

In [72]:
print(c+b)
c+b

[[1.00000000e+000 2.00000000e+000 3.00000000e+000]
 [3.00000000e+000 8.00000000e+000 6.95181563e-310]]


array([[1.00000000e+000, 2.00000000e+000, 3.00000000e+000],
       [3.00000000e+000, 8.00000000e+000, 6.95181563e-310]])

그래서 이번에는 c를 행렬로 전환하였고 2차원 배열에서 2x3 행렬을 얻을 수 있었다.

In [73]:
c=np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


행렬의 사칙연산이 가능해졌다. 덧셈이 완료되었다.

In [76]:
print(b+c)

[[ 2  4  6]
 [ 6 16  0]]


그런데 곱셈에는 문제가 발생하였다. value 에러가 발생하였고 설명을 보니 2x3 행렬과 2x3행렬은 곱셈이 불가능하다는 설명인 듯하다.

In [79]:
print(c*c)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

그래서 transpose 기능을 이용하여 2x3 행렬을 3x2로 전치하였고, 행렬의 곱셈이 가능해졌다.

In [80]:
c*c. T

matrix([[14, 19],
        [19, 73]])

우리가 b는 아직 2차원배열인 상태를 유지하고 있었는데, transpose함수를 사용하여 행렬처럼 곱셈을 하는것은 불가능했다.

In [81]:
b*b. T

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [82]:
b. T

array([[1, 3],
       [2, 8],
       [3, 0]])